"""rename

Revision ID: 27006133b668
Revises: 5a5d78954c4e
Create Date: 2025-05-26 16:52:54.493825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27006133b668"
down_revision: Union[str, None] = "5a5d78954c4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("name", sa.String(length=30), nullable=False, server_default=""),
    )
    op.drop_column("tasks", "name_tsk")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("name_tsk", sa.VARCHAR(), nullable=False))
    op.drop_column("tasks", "name")
    # ### end Alembic commands ###
